version: '3.8'

services:
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DB: toiletteFinder
      POSTGRES_USER: toiletteMaster
      POSTGRES_PASSWORD: fS3OFS6w52Z{5DiVj.VTts[[@
    ports:
      - "6969:5432"
    volumes:
      - ./volume/data:/var/lib/postgresql/data
  web:
    build:
      dockerfile: Dockerfile
    restart: always
    ports:
      - "69:8000"
    depends_on:
      - db