# Generated by Django 4.2.7 on 2024-03-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toilet',
            name='toiletDownVoteDeux',
            field=models.IntegerField(default=0),
        ),
    ]
