# Generated by Django 4.2.7 on 2024-03-06 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toilet', '0002_toilet_toiletdownvotedeux'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toilet',
            name='toiletDownVoteDeux',
        ),
    ]
